[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["day1"]

[workspace.dependencies]
tracing = "0.1.43"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
